- lib/generators/que/templates/add_que.rb
That. Means `rails generate que:install` will include the `retryable` column.
> Update default migration version to include retryable column

- CHANGELOG.md
- lib/que/job.rb
- lib/que/version.rb
- spec/unit/pool_spec.rb
Que should handle job arguments in a consistent manner regardless of
Que.mode. In the past when Que.mode is :sync then Que calls the run
method with whatever you have passed- this means arguments such as
symbol hashes (`{key: 'value'}`) would be passed unchanged, while if
this was enqueued and picked up by a Que worker from the database, the
hash would have string keys (`{'key' => 'value'}`).
The usage of Que.mode :sync is really reserved for testing environments,
where handling job args differently from how they will be used in
production can make tests pass when really they should fail. This change
makes Que fully serialize and then deserialize the job arguments to
ensure we run jobs with the arguments they will see in production.
> Enforce serialization on synchronous jobs

- CHANGELOG.md
- lib/que/adapters/base.rb
- lib/que/version.rb
Cherry-picked from upstream; this fixes a security vuln where untrusted user input as job args could instantiate arbitrary Ruby classes.
> Remove JSON.load/dump in favour of parse/generate

- lib/que/job.rb
- spec/unit/pool_spec.rb
When setting `Que.mode = :sync`  arguments that are passed to a job may not be the same to the ones that are passed when `Que.mode = :async`. For example, passing a `Time` in `async` mode will result in the job receiving a string, however, in `sync` mode the job will receive a `Time`.
To ensure that `sync` mode matches the behaviour of `async` mode, we must:
- serialise the job arguments
- deserialise the job arguments
- run the `Que.json_converter`
> Serialise and deserialise job args in sync mode

- que.gemspec
We now [use][1] ActiveSupport in `Que::Job`. This dependency isn't declared in the gemspec, so it can cause projects using Que to blow up (e.g. [que-failure][2]).
This declares the dependency on `activesupport`. I haven't specified a specific version because the method calls I've identified which require `active_support/core_ext` are using sugary `Hash` methods that have been around for a while.
[1]: https://github.com/gocardless/que/blob/master/lib/que/job.rb#L1-L2
[2]: https://circleci.com/gh/gocardless/que-failure/17?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
> Declare the gem's dependency on ActiveSupport

- lib/que.rb
- lib/que/worker.rb
The job variable is actually a HashWithIndifferentAccess instance, which
screws up any serialization your log formatter might do downstream. to_h
will get us a plain Ruby Hash which will play much better.
> Prevent logging HashWithIndifferentAccess

- lib/que/worker.rb
We had omitted the job class from the log keys that we were associating
with our logging events. This adds it back in, and amends a small issue
where id wasn't using `job_id`.
> Add job class to log keys

- Gemfile
- bin/que
- lib/que.rb
- lib/que/job.rb
- lib/que/locker.rb
- lib/que/sql.rb
- lib/que/worker.rb
- spec/lib/que/locker_spec.rb
- spec/lib/que/worker_spec.rb
https://brandur.org/postgres-queues
Extract locking into a separate object which tracks the last locked job
ID as a cursor for subsequent locking queries. This adaption pushes back
the point at which high dead tuple counts in the que_jobs table will
affect the lock query.
> Que::Locker with performance patch

- bin/que
- docs/shutting_down_safely.md
This allows us to deal with the situation where a job using the
`NoRetry` strategy takes a long time to complete. Normally this would
result in the process being forcibly killed (SIGKILL) by our scheduler. By
setting this timeout to just under the time between SIGTERM and SIGKILL, we
can ensure that the job fails cleanly, with a clear error message.
Only the last commit needs review, of course. The rest is rebased off our existing priority threshold branch.
> Add a timeout to the worker shutdown procedure

- bin/que
Fixes two things:
- an embarrassing bug in the timeout code that would cause Que to loop forever
- a bug that defaults the timeout code to active and the timeout to 0, which while largely harmless isn't really the behaviour that existing users will expect.
> Only run timeout code if flag is provided

- lib/que/worker.rb
- spec/lib/que/worker_spec.rb
This brings the log format in line with some of our conventions:
- Adds `handler` property to job work logs
- Adds `que_job.` prefix to job work logs (Que-related logs already have the `que.` prefix, e.g. [here](https://github.com/gocardless/que/blob/d4cc2748b4b5685426f94e48eb1296ee1f7d8b4a/lib/que/worker.rb#L36))
- Renames `id` to `que_job_id`
DET-78
> Work logging tweaks

- benchmark/setup.rb
- benchmark/start-worker
- bin/que
- docs/shutting_down_safely.md
- lib/que/metrics.rb
- lib/que/worker.rb
- spec/helpers/sleep_job.rb
- spec/integration/integration_spec.rb
- spec/spec_helper.rb
Allow creation of a threaded Que worker pool. This used to be in Que,
but was removed during a tidy-up.
The new threaded pool incorporates the work done on stop timeouts to
ensure we mark Que jobs as having failed, with the associated exception,
if the worker is requested to stop but fails to do so in time.
Notable changes include the removal of the --timeout-message flag (given
this can be provided by the Que::JobTimeoutError exception) and the
namespacing of the JobTimeoutError under the Que module. This will
require a small change in QueFailure.
> Threaded workers (--worker-count)

- lib/que/metrics.rb
Some job metrics lack base labels because a prior change has dropped the
code that merges them. This commit changes this to add the base labels
back to all our metrics.
> Fix metric labels

- CHANGELOG.md
- lib/que/version.rb
We've made several large changes to Que recently, some of which are
breaking. We should bump to a new major version so that dependent gems
like que-failure can specify which version they lock against.
> Bump to v1.0.0

- lib/que.rb
- lib/que/job_timeout_error.rb
- lib/que/worker.rb
**Why?**
We've found this alarming pattern all over the worker codebase: https://github.com/gocardless/payments-service/blob/master/app/workers/mark_credits_as_paid.rb#L69
This outcome of this is we're absorbing `Que::JobTimeoutError` and the job is managing to finish "successfully" as a result, meaning it's not automatically retried. It's not practical to require on FR intervention for every individual instance of this.
As a result, we're going to need to add a varying amount of `raise if error.is_a?(Que::JobTimeoutError)` into examples like the above so we force the job to fail so it can be retried properly. PR here for that: https://github.com/gocardless/payments-service/pull/15881
In the long run, we're going to want to clean up this "rescue everything" pattern. However, with a few …
> Enable autoloading of Que::JobTimeoutError

- .circleci/config.yml
- Gemfile
- bin/que
- lib/que.rb
- lib/que/leaky_bucket.rb
- lib/que/locker.rb
- lib/que/worker.rb
- spec/lib/que/leaky_bucket_spec.rb
- spec/spec_helper.rb
Enable users to throttle Que locking queries to better handle situations
where job acquisition becomes expensive. The LeakyBucket class attempts
to fairly throttle the lock acquisition by sleeping during the lock
process, aiming to satisfy the at-most budget seconds of lock work per
window.
> que --lock-window <window> --lock-budget <budget>

- lib/que/middleware/queue_collector.rb
- lib/que/migrations.rb
- lib/que/migrations/5/down.sql
- lib/que/migrations/5/up.sql
- spec/lib/que/middleware/queue_collector_spec.rb
Instead of re-computing this every time we scrape, use a materialized
view to avoid hurting the database. This makes it more sensible to
output queue metrics from each Que worker, too.
> Materialized view for job counts

- lib/que/leaky_bucket.rb
- lib/que/locker.rb
- spec/lib/que/leaky_bucket_spec.rb
The previous commit didn't actually use the observe method of the leaky
bucket. This meant the bucket never tracked any work, so while the
bucket itself worked, it never took any throttling action.
We also provide an improvement to the observe method of the leaky bucket
to ensure we throttle things even when the lock timeout throws an
exception.
> Assorted fixes for the leaky bucket

- lib/que/adapters/base.rb
Without this, floats are returned as strings back to que, causing the
'latency' argument of the `lock_job` query to be incorrectly
deserialised when not using the ActiveRecord adapter (as ActiveRecord
will automatically cast some values to the correct type).
A full list of datatypes and their internal constant representation
can be found in https://jdbc.postgresql.org/documentation/publicapi/constant-values.html,
but looks like `FLOAT8` is what's being returned in most cases.
> Support correct deserialization of floats

- lib/que/adapters/base.rb
- spec/lib/que/job_spec.rb
This is especially true in ActiveRecord 5+ as they are already returning
booleans in postgres as ruby booleans. This causes the field type on the
PG raw resultset to be set to bool (`16`) and therefore all booleans end
up being inverted because `'t' == true` returns `false`.
See #60 for more context
Upstream que also has had the same fix a while ago: https://github.com/que-rb/que/commit/88d1cae8249afc091438e22f52444bccdefe5c1a
> Correctly handle booleans for adapters that do their own type casting

- que.gemspec
We don't need to pin bundler to any version here, especially the 1.3
version which is about 8 years old at this stage.
This means we can run `bundle install` again for que without running
into conflicts as most of everything runs on bundler 2.x.
Alternatively we could pin this to '~> 2` but in every other gem we own
we're not doing this explicitly and I think it works well in practice
> Remove bundler as a dev dependency

- .circleci/config.yml
We're getting warnings that we're not authenticated against docker hub
and they'll be restricting access to these images at some point.
> Use CircleCI's docker image

- lib/que/middleware/worker_collector.rb
- lib/que/worker_group.rb
We ran into a case last week where one of our workers failed to check
out a connection from ActiveRecord, leaving a worker running without
actually processing any jobs. Turns out that we have limited visibility
into this and it's possible this is happening more frequently but we
haven't noticed (yet) as no errors are reported anywhere and if you have
more than one worker (as in, more than one executable worker) things
will be working normally, though with a lower throughput.
The fact that the error is completely hidden is a bit worrying, but I'll look
at that separately. This PR focuses on the metrics visibility aspect of
the problem.
Each que "worker" (as an executable) will spawn a _worker group_, which is
a collection of threads that will end up picking up the jobs on the
configured …
> Export metrics for worker groups

- lib/que/adapters/active_record.rb
- lib/que/adapters/base.rb
- lib/que/worker.rb
- spec/lib/que/worker_spec.rb
It's possible for the adapter to not being able to checkout a new PG
connection. In the case of AR specifically, this can raise a few
different exceptions depending on what's the reason behind the failure.
Currently when AR raise a connection timeout, the thread won't catch
that exception, meaning that it will crash and leave the worker with one
less thread available to process job. In cases where we only use a
single thread (the default case), this means it's possible for a worker
to be up and running but not actually processing any new jobs.
This commit introduces a way to recognise those exceptions and let the
thread retry on failure, so that we're not left with stale workers.
> Do not kill the worker thread if we can't checkout a PG connection

- lib/que/adapters/active_record.rb
- spec/lib/que/worker_spec.rb
Just like #66, we've seen instances of a que worker using fewer threads
than desired after failing to check out a connection from AR. In some
cases, this can lead to a worker doing nothing (specifically, this can
happen if the que worker is configured to run with a single thread -- if
that thread dies, the worker will sit idle doing nothing forever).
This commit lets the ActiveRecord adapter handle the case where the
connection could not be estabilished for reasons other than a timeout,
which was already handled. Additionally, the internal
`UnavailableConnection` exception will also now include the original
exception as a nested `.cause` attribute to aid debugging.
> Do not kill the worker thread on connection timeouts

- lib/generators/que/templates/add_que.rb
When no argument is provided, it uses latest version by default:
https://github.com/gocardless/que/blob/29646821821d1d18ac2944584e55255c57d8f957/lib/que.rb#L105
which means we don't need to keep this file in sync (it is one version behind right now)
> Use latest version of Que migration by default

- lib/que/worker_group.rb
This means that the threads actually running the application code will
be easily identifiable when inspected (either by means of `cat
/proc/<pid>/task/<tid>/status` or by running `Thread.list`).
> Name the worker threads

- lib/que/worker.rb
When a job fails, the worker (thread) processing the job normally marks
the job as failed and picks up another job. That is unless the job fails
with an error that doesn't inherit from `StandardError` (or
`JobTimeoutError`).
`NotImplementedError` is one of those errors, which means that if
a job fails with this error, the worker will crash, causing some
[headaches][1].
This error is widely [(ab)used][2] in Rails and in our own codebase so
we're better off rescuing it.
Ref: https://gocardless.slack.com/archives/C01JMFWJW2Z/p1632300910114400
[1]: https://gocardless.slack.com/archives/C01JMFWJW2Z/p1632300910114400
[2]: http://chrisstump.online/2016/03/23/stop-abusing-notimplementederror/
> Rescue `NotImplementedError`s

- lib/que/worker.rb
This log happens when there is no work on the workers queue and isn't particularly useful in production. If we want to assess if the queue is being over provisioned we should instead look at the SleepingSecondsTotal metric.
I've preserved the postgres_error log at its current level, its likely this is at the wrong level also and should be higher but its likely we'd see other more useful errors alongside this.
> Downgrade que.job_not_found log to debug

- bin/que
- lib/que/locker.rb
- lib/que/sql.rb
- lib/que/worker.rb
- spec/integration/integration_spec.rb
- spec/lib/que/worker_spec.rb
This allows workers to be better utilised by picking up work from other queues if they are idle. 
Some caveats for this:
* Workers need to be roughly the same size, i.e. similar cpu / memory to avoid creating OOM issues - Because of this we should only use this on compatible queues
* We need to evaluate the impact of the changes to the polling queue query
* Assumptions made about the number of workers on a queue will break; this may result in bottlenecks being moved.
Usage
```
usage: que [options] file/to/require ...
....
--secondary-queues high_priority_queue,low_priority_queue
Sets the queues to poll for multiple queue consumption
```
> Permissive worker

- bin/que
This avoids passing a nil values into Locker which will cause an issue starting the process.
> Add a default value for secondary_queues

- README.md
- lib/que/worker.rb
- spec/lib/que/worker_spec.rb
Follow on from https://github.com/gocardless/que/pull/93
Allows us to break down when a queue is stealing work from another queue
> Add metric label for primary_queue

- lib/que/locker.rb
- lib/que/sql.rb
Rather than attempt to modify the query to select one job from multiple queues in the DB we instead call into the DB multiple times.
This means we can rely on the existing query planning used for single queue collections while still getting prioritised work stealing.
It comes with two trade offs:
1. This is obviously less efficent in terms of Database time for cases where queues are empty. With cursor resetting this is compounded meaning a worker servicing 2 queues can in theory make 4 DB queries and not find any work. To offset this the idea is that with work stealing we can have less replicas for the amplification effect is reduced. In addition we have Leaky Bucket throttling to ensure we don't overwhelm the DB.
2. This could lead to circumstances where higher priorities queues are …
> [RFC] Allow selection from multiple queues at the application level

- lib/que/adapters/active_record.rb
- lib/que/adapters/base.rb
- spec/lib/que/job_spec.rb
When executing queries via the adapter, we may not recieve the instrumentation we expect. The ActiveRecord adapter uses a raw connection which bypasses the ActiveRecord instrumentation layer and instead talks directly to PG, making it impossible to know what queries are being executed.
This change cribs heavily from the implementation of the `log` method on the `AbstractAdapter` class in ActiveRecord to make it easy to add instrumentation to an adapter. By default the instrumenter is set to `nil`, and instrumentation will be a no-op; otherwise the query will be instrumented via the `instrument` method and passed the relevant payload to handle. The structure of this is deliberately similar to that of the event emitted by ActiveRecord's `sql.active_record` notification.
> Instrument adapter queries for external programs.

- .github/workflows/tests.yml
- lib/que.rb
- lib/que/adapters/active_record_with_lock.rb
- lib/que/adapters/base.rb
- lib/que/locker.rb
- lib/que/sql.rb
- spec/active_record_with_lock_spec_helper.rb
- spec/lib/que/locker_spec.rb
- spec/spec_helper.rb
What?
Added a new adapter which uses 2 databases to work the job. 
database 1 will have the job enqueued and will fetch the jobs to be worked
database 2 will be used to acquire the advisory lock on the job.
This adapter can be used with a database that does not support advisory locking.  In the above scenario, database 1 does not support advisory locking.
> Add a new adapter to work the job with multiple database

- .rubocop.yml
- lib/que/adapters/active_record.rb
- spec/lib/que/worker_spec.rb
With the introduction of Yugabyte, there is now the possibility that connections in the pool may become "dead" when new nodes are rotated into a cluster, since they end up pointing at a node which no longer exists. In this case, we can proactively remove these connections from the connection pool when we see the corresponding exceptions.
As long as jobs are retryable the work will still eventually be processed - this merely prevents us from being stuck in a pathological case where the pool contains dead connections and nothing is automatically clearing them out (e.g. a deployment killing the pod).
> Remove dead connections from the pool on connection errors.

- .github/workflows/tests.yml
- Gemfile
- bin/que
- que.gemspec
WEBrick appears to be approaching EOL and is being removed from Rackup, as mentioned [here](https://github.com/rack/rackup/blob/main/readme.md#soft-deprecation). This is causing issues with a number of services as discussed [here](https://gocardless.slack.com/archives/C6ZKC4F4L/p1730735504149619). By switching to Puma we can solve this issue while also still supporting both Rack 2 and 3.
> Switch from WEBrick to Puma
